# Generated by Django 2.2.1 on 2019-10-30 19:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time_stamp',
            field=models.DateField(default=datetime.datetime(2019, 10, 30, 19, 44, 54, 661503, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.DateField(default=datetime.datetime(2019, 10, 30, 19, 44, 54, 651498, tzinfo=utc)),
        ),
    ]
