# Generated by Django 2.2.1 on 2019-11-02 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191102_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time_stamp',
            field=models.DateField(default=datetime.datetime(2019, 11, 2, 18, 56, 32, 850384, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.DateField(default=datetime.datetime(2019, 11, 2, 18, 56, 32, 850384, tzinfo=utc)),
        ),
    ]
