# Generated by Django 2.2.1 on 2019-11-02 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191103_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time_stamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
